{% set name = "edlib-python" %}
{% set version = "1.2.3.post1" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "622ea738c177ea1c5f131a137c37599daba55c8d75875d51e93a5a980b2ae5be" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/edlib/edlib-{{ version }}.{{ file_ext }}
  sha256: '{{ hash_value }}'
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - edlib
test:
  imports:
    edlib
about:
  home: https://pypi.org/project/edlib/
  license: MIT
  license_family: MIT
  license_file: ''
  summary: Lightweight, super fast library for sequence alignment using edit (Levenshtein) distance.
  description: "Python wrapper for edlib, lightweight, super fast library for sequence alignment using edit (Levenshtein) distance."
  doc_url: ''
  dev_url: ''
extra:
  recipe-maintainers: 'pb-cdunn'
